name: tabnewsnc
description: "Cliente para visualizar e interagir com as not√≠cias/artigos publicados no TabNews"

publish_to: "none"
homepage: https://softyes.com.br
repository: https://github.com/TabNewsNC/tabnewsnc_mobile

version: 0.4.0+5

environment:
  sdk: ^3.10.3
  flutter: ^3.38.4

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.4.1
  get: ^4.6.6
  hive: ^2.2.3
  ionicons: ^0.2.2
  markdown: ^7.2.1
  solar_icons: ^0.0.5
  share_plus: ^12.0.1
  google_fonts: ^6.1.0
  url_launcher: ^6.2.5
  dart_mappable: ^4.0.1
  feather_icons: ^1.2.0
  path_provider: ^2.1.4
  icons_launcher: ^3.0.3
  cupertino_icons: ^1.0.2
  flutter_markdown: ^0.7.1
  tabnewsnc_ui:
    path: ../tabnewsnc_ui
  tabnewsnc_engine:
    path: ../tabnewsnc_engine

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  flutter_lints: ^6.0.0
  very_good_analysis: ^10.0.0
  flutter_native_splash: ^2.3.13
  dart_mappable_builder: ^4.0.1
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/
